version: "3.3"
services:
  app:
    image: your_app_image
  db:
    image: postgres
  cache:
    image: redis
  notification:
    image: your_notification_service
  Sms:
    image: your_sms_service
    environment:
      Sms__MessageTemplate: "Notio dogrulama kodunuz: {code}"
