apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notioedu-k8s-tls
  namespace: default
spec:
  secretName: notioedu-k8s-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - k8s.notioedu.com
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notioedu-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - k8s.notioedu.com
      secretName: notioedu-k8s-tls
  rules:
    - host: k8s.notioedu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notioedu-service
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notioedu-registry-tls
  namespace: registry
spec:
  secretName: notioedu-registry-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - registry.notioedu.com
  usages:
    - digital signature
    - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zot-registry
  namespace: registry
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/client-body-buffer-size: "1m"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - registry.notioedu.com
      secretName: notioedu-registry-tls
  rules:
    - host: registry.notioedu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zot-registry
                port:
                  number: 80
