image:
  repository: registry.notioedu.com/notio/notio-web
  tag: "1.0.0"
  pullPolicy: Always

imagePullSecrets:
  - name: reg-hub-secret

namespace: notio

replicaCount: 1

service:
  port: 80

ingress:
  host: platform.notioedu.com
  additionalHost: platform.notioedu.com
  tlsSecret: notioedu-wildcard-tls
  clusterIssuer: letsencrypt-prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
  apiBackend:
    service: edulink-api
    port: 80

readinessProbe:
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10
